# Limpieza II

<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Trabajando-con-strings" data-toc-modified-id="Trabajando-con-strings-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Trabajando con strings</a></span></li><li><span><a href="#Creación-de-nuevas-columnas-basadas-en-columnas-ya-existentes" data-toc-modified-id="Creación-de-nuevas-columnas-basadas-en-columnas-ya-existentes-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Creación de nuevas columnas basadas en columnas ya existentes</a></span><ul class="toc-item"><li><span><a href="#Creación-de-intervalos:-pd.cut()" data-toc-modified-id="Creación-de-intervalos:-pd.cut()-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Creación de intervalos: <code>pd.cut()</code></a></span></li><li><span><a href="#Creación-de-porcentajes" data-toc-modified-id="Creación-de-porcentajes-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Creación de porcentajes</a></span></li><li><span><a href="#Creación-de-Ratios" data-toc-modified-id="Creación-de-Ratios-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Creación de ratios</a></span></li><li><span><a href="#Otras-formas-de-modificar-una-columna-o-dataframe-al-completo:" data-toc-modified-id="Otras-formas-de-modificar-una-columna-o-dataframe-al-completo:-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span>Otras formas de modificar una columna o dataframe al completo:</a></span></li></ul></li><li><span><a href="#Tratamiento-de-outliers-o-valores-perdidos" data-toc-modified-id="Tratamiento-de-outliers-o-valores-perdidos-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Tratamiento de <em>outliers</em> o valores perdidos</a></span><ul class="toc-item"><li><span><a href="#Eliminar-outliers" data-toc-modified-id="Eliminar-outliers-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Eliminar <em>outliers</em></a></span></li><li><span><a href="#Reemplazar" data-toc-modified-id="Reemplazar-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>Reemplazar</a></span></li></ul></li></ul></div>

In [18]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

pd.options.display.max_columns = None

En este jupyter volveremos a trabajar con el mismo *dataset*, pero en este caso no trabajaremos con el orginal, si no con el que habíamos guardado que ya tenía algunas modificaciones (*WDICountry_limpio*). Así que... empecemos cargándolo y explorándolo:

In [19]:
df = pd.read_csv("files/WDICountry_limpio.csv", index_col = 0)
df.head(2)

,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016
index_,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308
2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857

In [20]:
# lo primero que vamos a hacer es resetar el index para tener esos valores como columna en nuestro df. 
df.reset_index(inplace = True)

In [21]:
df.head(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016
0,0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308
1,2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857

## Creación de nuevas columnas basadas en columnas ya existentes

En algunas ocasiones nos podeomos encontrar columnas con *strings* que están bastante "sucias". Podemos tener columnas que contegan demasiada información y que queramos separar en distintas columnas, o crear intervalos en función de los valores de una columna o incluso podemos crear columnas que nos indiquen porcentajes o ratios. En este apartado veremos como podemos hacer todo esto de una forma muy sencilla usando Pandas 👯.

### Separar una columna en dos

Exploremos la columna `latest_household_survey`.

In [22]:
df["latest_household_survey"].unique()[:10]

array([nan, 'Demographic and Health Survey, 2015',
       'Demographic and Health Survey, 2015/16',
       'Demographic and Health Survey, 2017/18',
       'World Health Survey, 2003',
       'Multiple Indicator Cluster Survey, 2019/20',
       'Demographic and Health Survey, 2006',
       'Demographic and Health Survey, 2016/17',
       'Malaria Indicator Survey, 2017/18',
       'Multiple Indicator Cluster Survey, 2019'], dtype=object)

Si nos fijamos esta columna hace referencia a cuando se hizo el último muestreo. Sin embargo, es una columna de tipo *string* y tiene más información a parte de los años. 

Lo que vamos a hacer es quedarnos únicamente con los números (con los años). Para ello nos vamos a usar el método propio de pandas `str.split()`.

Este método va a **dividir *strings* basándose en un separador/delimitador dado**.

Su sintaxis: 

```python
    columna.str.split(pat=None, n=- 1, expand=False, *, regex=None)
```

Donde: 

- `pat`: str o regex, opcional. Cadena o expresión regular para dividir. Si no se especifica, se divide en espacios en blanco. Si especificamos por `";"` dividiremos por `;`. 

- `n`: int, por defecto `-1` (todos). Limita el número de divisiones. `None`, `0` y `-1` serán interpretados como la devolución de todas las divisiones.

- `expand`: bool, por defecto `False`. Separa las strings divididas en columnas separadas.

    - Si es `True`, devuelve tantas columnas nuevas como divisiones.
    - Si es `False`, devuelve una única columna con una lista donde tendremos todas las divisiones. 

- `regex`:  

    - Si es `True`, asume que el patrón pasado es una expresión regular.
    - Si es `False`, trata el patrón como una cadena literal.

Cosas que debemos tener en cuenta para crear la función 

- Tenemos `nan` por lo que tendremos que hacer un `try`, `except` para evitar que nos de errores. 
- Los años vienen siempre después de una coma, por lo que tendremos que usar el método `split` de los *strings*.

In [23]:
df[['survey_place','year_survey']] = df['latest_household_survey'].str.split(',', expand=True, n=1)

In [24]:
df.sample(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey
111,149,Moldova,13.7,1.241,Moldova,MD,Moldovan leu,"Excluding Transnistria. For 1950-94, World Ban...",Europe & Central Asia,Upper middle income,MD,Original chained constant price data are resca...,2010.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,1990–95,BPM6,Actual,General trade system,Consolidated central government,Special Data Dissemination Standard (SDDS),2014,"Multiple Indicator Cluster Survey, 2012","Expenditure survey/budget survey (ES/BS), 2017",Yes,2011,2012.0,2018.0,37,7437436,Multiple Indicator Cluster Survey,2012
41,52,Cayman Islands,NaN,NaN,Cayman Islands,KY,Cayman Islands dollar,NaN,Latin America & Caribbean,High income,KY,2015,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,NaN,NaN,NaN,2020 (expected),NaN,NaN,Yes,NaN,NaN,2015.0,66,2097015,NaN,NaN

Si nos fijamos se nos han creado dos columnas nuevas llamadas `survey_place` y `year_survey`, donde en la primera tendremos el sitio donde se hizo la encuesta y en la segunda los años👏🏽.

### Creación de intervalos: `pd.cut()`

```python
    pd.cut(x, bins, right=True, labels=None, ordered=True)
```

Donde: 

- `x`: la columna que vamos a querer dividir. La matriz de entrada que se va a dividir. Debe ser unidimensional.

- `bins`: integer, el número de intervalos en el que queremos dividir nuestra columna. 

- `labels`: array o `False`, por defecto `None`.
Especifica las etiquetas de los intervalos devueltos. Deben tener la misma longitud que los intervalos resultantes. Si es `False`, devuelve sólo indicadores enteros de los bins. Si es `True`, genera un error si no coincide. Cuando `ordered=False`, se deben proporcionar las etiquetas.

- `ordered`: bool, por defecto `True`. Si las etiquetas están ordenadas o no. Si es `False`, la columna resultante no estará ordenado (se deben proporcionar las etiquetas).

In [25]:
df["age_bins"] = pd.cut(df["mean_age"], 3, labels = ["grupoA", "grupoB", "grupoC"])

In [26]:
df.sample(10)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins
63,84,Gibraltar,NaN,NaN,Gibraltar,GI,Gibraltar pound,NaN,Europe & Central Asia,High income,GI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2012,NaN,NaN,Yes,NaN,NaN,NaN,84,7433904,NaN,NaN,grupoC
70,92,Guatemala,23.9,2.973,Guatemala,GT,Guatemalan quetzal,NaN,Latin America & Caribbean,Upper middle income,GT,Original chained constant price data are resca...,2013.0,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,NaN,BPM6,Actual,Special trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2018,"Demographic and Health Survey, 2014/15",Living Standards Measurement Study Survey (LSM...,Yes,NaN,1988.0,2017.0,43,1642879,Demographic and Health Survey,2014/15,grupoA
40,50,Cuba,4.2,1.722,Cuba,CU,Cuban peso,NaN,Latin America & Caribbean,Upper middle income,CU,1997,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,NaN,NaN,NaN,NaN,NaN,2012,"Multiple Indicator Cluster Survey, 2019",NaN,Yes,NaN,1989.0,2006.0,86,760478,Multiple Indicator Cluster Survey,2019,grupoC
157,208,Solomon Islands,21.8,3.850,Solomon Islands,SB,Solomon Islands dollar,NaN,East Asia & Pacific,Lower middle income,SB,2012,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,Special trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2019,"Solomon Islands Demographic and Health Survey,...","Integrated household survey (IHS), 2012/13",NaN,NaN,NaN,2018.0,50,3586060,Solomon Islands Demographic and Health Survey,2006/07,grupoA
154,205,Sudan,44.8,4.532,Sudan,SD,Sudanese pound,NaN,Sub-Saharan Africa,Low income,SD,1996,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1968 System of National Accou...,NaN,BPM6,Preliminary,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),"Multiple Indicator Cluster Survey, 2014","Expenditure survey/budget survey (ES/BS), 2009",NaN,NaN,2001.0,2017.0,69,8072192,Multiple Indicator Cluster Survey,2014,grupoB
17,20,Bangladesh,28.2,2.104,Bangladesh,BD,Bangladeshi taka,Fiscal year end: June 30; reporting period for...,South Asia,Lower middle income,BD,2006,NaN,Value added at basic prices (VAB),IDA,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2016",NaN,2008,2011.0,2015.0,68,3378278,Multiple Indicator Cluster Survey,2019,grupoB
128,171,New Caledonia,NaN,2.080,New Caledonia,NC,CFP franc,NaN,East Asia & Pacific,High income,NC,1990,NaN,Value added at producer prices (VAP),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,NaN,2019,NaN,NaN,Yes,NaN,NaN,2015.0,41,9128972,NaN,NaN,grupoA
125,167,Malawi,38.9,4.571,Malawi,MW,Malawi kwacha,NaN,Sub-Saharan Africa,Low income,MW,2017,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 2008 System of National Accou...,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2018,Fifth Integrated Household Survey 2019-2020; M...,"Integrated household survey (IHS), 2016",NaN,2006-2007,2012.0,2017.0,60,8953060,Fifth Integrated Household Survey 2019-2020; M...,2019/20,grupoB
127,170,Namibia,32.3,3.415,Namibia,NaN,Namibian dollar,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,NaN,2015,NaN,Value added at basic prices (VAB),IBRD,NaN,Country uses the 2008 System of National Accou...,NaN,BPM6,NaN,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2015",NaN,2013-2014,2013.0,2018.0,30,2009524,Demographic and Health Survey,2013,grupoA
138,183,Pakistan,64.2,3.481,Pakistan,PK,Pakistani rupee,Fiscal year end: June 30; reporting period for...,South Asia,Lower middle income,PK,2005/06,NaN,Value added at basic prices (VAB),Blend,NaN,Country uses the 2008 System of National Accou...,NaN,BPM6,Actual,General trade system,Budgetary central government,Enhanced General Data Dissemination System (e-...,2017,Pakistan Maternal Mortality Survey\nOther Data...,"Integrated household survey (IHS), 2014/15",NaN,2010,2006.0,2018.0,36,6311130,Pakistan Maternal Mortality Survey\nOther Data,2019,grupoA

In [27]:
df["age_bins"].unique()

['grupoA', 'grupoC', 'grupoB']
Categories (3, object): ['grupoA' < 'grupoB' < 'grupoC']

### Creación de porcentajes

In [28]:
df.head(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins
0,0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA
1,2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857,Demographic and Health Survey,2015,grupoC

En este apartado utilizaremos las columnas de `m2016` y `f2016`, las cuáles indican el número de defunciones y nacimientos respectivamente en cada pais. 

Para esto nos crearemos una función para calcular el porcentaje de nacidos en función de toda la población.

In [29]:
def porcentaje(nacidos, total): 
    return (nacidos * 100) / total

In [30]:
df["porcentaje_nacidos"] = df.apply(lambda datos: porcentaje(datos["f2016"], datos["total2016"]), axis = 1)

In [31]:
df.head(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins,porcentaje_nacidos
0,0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA,0.000289
1,2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857,Demographic and Health Survey,2015,grupoC,0.000128

Lo podemos hacer de una forma más sencilla sin usar funciones:

In [32]:
df["porcentaje_nacidos2"] = (df["f2016"] * 100) / df["total2016"]

In [33]:
df.head(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins,porcentaje_nacidos,porcentaje_nacidos2
0,0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA,0.000289,0.000289
1,2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857,Demographic and Health Survey,2015,grupoC,0.000128,0.000128

### Creación de Ratios

La diferencia entre ratio y porcentaje es mínima: 

- `ratio`:  es el cociente


- `porcentaje`: es el cociente multiplicado por cien (expresado como tanto por ciento).

En este caso calcularemos el ratio de nacidos, y usaremos una `lambda`.

In [34]:
df["ratio_nacidos"] = df.apply(lambda df: df["f2016"] / df["total2016"], axis = 1)

In [35]:
df.head(2)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins,porcentaje_nacidos,porcentaje_nacidos2,ratio_nacidos
0,0,Aruba,NaN,1.800,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA,0.000289,0.000289,0.000003
1,2,Afghanistan,53.2,4.635,Afghanistan,AF,Afghan afghani,Fiscal year end: March 20; reporting period fo...,South Asia,Low income,AF,2016,NaN,Value added at basic prices (VAB),IDA,HIPC,Country uses the 1993 System of National Accou...,NaN,BPM6,Actual,General trade system,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2018.0,80,3607857,Demographic and Health Survey,2015,grupoC,0.000128,0.000128,0.000001

## Otras formas de modificar una columna o DataFrame al completo: 

En Pandas tenemos:

- `apply`: se puede aplicar tanto al DataFrame completo como a una sola columna, ya lo hemos visto.

- `pd.applymap`: se puede aplicar solo a todo el DataFrame.

- `map`: solo lo podremos aplicar a una columa en particular. 

Veamos los dos nuevos uno a uno:

### `pd.applymap`

Aplica una función a un Dataframe por elementos, es decir, similar al `apply` que ya conocemos con la diferencia que este método se tiene que aplicar a **todo el dataframe**. 

Este método aplica una función que acepta y devuelve un escalar a cada elemento de un DataFrame.

``` python
    MiDataFrame.applymap(func, na_action=None, **kwargs)
```

Donde: 

- `func`: función de Python, devuelve un único valor a partir de un único valor.

- `na_action`: puede ser `None` o `'ignore'`, por defecto `None`.

    - Si es `'ignore'`, propaga los valores `NaN`, sin pasarlos a `func`. Es decir, ignora los nulos. 

- `**kwargs`: argumentos adicionales para pasar como argumentos de palabras clave a `func`.

In [36]:
# definimos nuestra lambda: 

scaled_df=df.applymap(lambda a: a + 10 if type(a) == int or type(a) == float else a, na_action = "ignore")

In [37]:
scaled_df.head(1)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins,porcentaje_nacidos,porcentaje_nacidos2,ratio_nacidos
0,10,Aruba,NaN,11.8,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2028.0,47,622318,NaN,NaN,grupoA,10.000289,10.000289,10.000003

In [38]:
df.head(1)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,survey_place,year_survey,age_bins,porcentaje_nacidos,porcentaje_nacidos2,ratio_nacidos
0,0,Aruba,NaN,1.8,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,General trade system,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA,0.000289,0.000289,0.000003

Si nos fijamos por ejemplo en la columna `m2016` vemos que los valores hay incrementado en 10. Esto es porque en nuestra lambda hemos definido que aquellos que sean *integers* o *floats* les sumaremos 10. En caso contrario dejaremos los valores originales.

In [39]:
# si intentaramos aplicarlo a una columna: 

scaled_df=df["mean_age"].applymap(lambda a: a + 10 if type(a) == int or type(a) == float else a, na_action = "ignore")

AttributeError: 'Series' object has no attribute 'applymap'

Nos sale un error y nos dice que el método `applymap` no se puede aplicar a `Series`. Por lo tanto: 

- `applymap`: únicamente para todo el `DataFrame`.

- `apply`: lo podemos aplicar tanto a todo el `DataFrame` como a una columna en concreto (una `Serie`).

### `map`

Mapea los valores de la columna de acuerdo a un mapeo o función dada.

Se utiliza para sustituir cada valor de una columna por otro valor, que puede derivarse de una función, un `dict` o una `Serie`.

Su sintaxis: 

```python
    MiColumna.map(arg, na_action=None)
```

Donde: 

- `arg`: function para mapear.

- `na_action`: puede ser `None` o `'ignore'`, por defecto `None`.

    - Si es `'ignore'`, no tiene en cuenta los nulos.

En la columna `system_of_trade` tenemos dos valores únicos diferentes. 

```python
    df["system_of_trade"].unique()
```

output

```console
    array(['General trade system', 'Special trade system', nan], dtype=object)
```

Imaginemos que queremos mapear estos valores para ponerlos como *integers*. Podríamos crearnos una función y aplicarla a nuestra columna. Pero tenemos el método `map` que nos lo va a permitir hacer de una forma más sencilla. 

Aunque ahora no le veamos mucho sentido a esta tranformación, nos puede resultar super útil cuando lleguemos a la parte de *machine learning*, ya que muchos modelos no aceptan variables categóricas y las tendremos que cambiar a valores numéricos. Es en este momento donde tendremos que usar el `map`. 

Veamos un ejemplo con un diccionario, que es la forma más usual de usar el `map`.

In [ ]:
# lo primero que tenemos que hacer es crear el diccionario para el mapeo
mapa = {"General trade system": 1, # donde los valores sean "General trade system" pondremos un 1
       "Special trade system": 2} # donde los valores sean "Special trade system" podremos un 0

In [ ]:
# ejecutamos la función map 
df["system_of_trade"] = df["system_of_trade"].map(mapa, na_action="ignore")

In [ ]:
# chequeamos los cambios. Ahora en la columna "system_of_trade" ya no tendremos los valores antiguos si no 1 y 2. 
df.head(1)

,index_,country_name,m2016,f2016,short_name,2-alpha_code,currency_unit,special_notes,region,income_group,wb-2_code,national_accounts_base_year,national_accounts_reference_year,sna_price_valuation,lending_category,other_groups,system_of_national_accounts,alternative_conversion_factor,balance_of_payments_manual_in_use,external_debt_reporting_status,system_of_trade,government_accounting_concept,imf_data_dissemination_standard,latest_population_census,latest_household_survey,source_of_most_recent_income_and_expenditure_data,vital_registration_complete,latest_agricultural_census,latest_industrial_data,latest_trade_data,mean_age,total2016,year_survey,survey_place,age_bins,porcentaje_nacidos,porcentaje_nacidos2,ratio_nacidos
0,0,Aruba,NaN,1.8,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,2000,NaN,Value added at basic prices (VAB),NaN,NaN,Country uses the 1993 System of National Accou...,NaN,BPM6,NaN,1.0,NaN,Enhanced General Data Dissemination System (e-...,2020 (expected),NaN,NaN,Yes,NaN,NaN,2018.0,37,622308,NaN,NaN,grupoA,0.000289,0.000289,0.000003

In [ ]:
df["system_of_trade"].unique()

array([ 1.,  2., nan])

In [ ]:
df.loc[28]

index_                                                                                              33
country_name                                                                                  Botswana
m2016                                                                                             32.6
f2016                                                                                             2.73
short_name                                                                                    Botswana
2-alpha_code                                                                                        BW
currency_unit                                                                            Botswana pula
special_notes                                                                                      NaN
region                                                                              Sub-Saharan Africa
income_group                                                                       Upper middle income
wb-2_code                                                                                           BW
national_accounts_base_year                                                                       2016
national_accounts_reference_year                                                                   NaN
sna_price_valuation                                                  Value added at basic prices (VAB)
lending_category                                                                                  IBRD
other_groups                                                                                       NaN
system_of_national_accounts                          Country uses the 1993 System of National Accou...
alternative_conversion_factor                                                                      NaN
balance_of_payments_manual_in_use                                                                 BPM6
external_debt_reporting_status                                                                  Actual
system_of_trade                                                                                    1.0
government_accounting_concept                                             Budgetary central government
imf_data_dissemination_standard                      Enhanced General Data Dissemination System (e-...
latest_population_census                                                                          2011
latest_household_survey                                                 Family Health Survey 2007-2008
source_of_most_recent_income_and_expenditure_data    Core Welfare Indicator Questionnaire Survey (C...
vital_registration_complete                                                                        NaN
latest_agricultural_census                                                                        2015
latest_industrial_data                                                                          2013.0
latest_trade_data                                                                               2018.0
mean_age                                                                                            58
total2016                                                                                      9305369
year_survey                                                             Family Health Survey 2007-2008
survey_place                                                                                      None
age_bins                                                                                        grupoB
porcentaje_nacidos                                                                            0.000029
porcentaje_nacidos2                                                                           0.000029
ratio_nacidos                                                                                      0.0
Name: 28, dtype: object

In [ ]:
# si intentaramos aplicar un map a toda un dataframe 
df_ = df.map(mapa, na_action="ignore")

AttributeError: 'DataFrame' object has no attribute 'map'

Nos sale un error y nos dice que el método `map` no se puede aplicar a un `DataFrame`. Por lo tanto: 

- `applymap`: únicamente para todo el `DataFrame`.


- `apply`: lo podemos aplicar tanto a todo el `DataFrame` como a una columna en concreto (una `Serie`).


- `map`: únicamente para columnas.

Por último vamos a guardar el csv con las columnas nuevas que hemos creado para seguir trabajando con él en la siguiente lección de limpieza.

In [ ]:
df.to_csv("datos/WDICountry_limpio.csv")

## Ejercicios

Usando el mismo `south.csv` que en la lección anterior, cárgalo y contesta a las siguientes preguntas: 

Antes de empezar, este *DataFrame* tiene muchas columnas y no las podemos visualizar todas en jupyter. Ejecuta la línea de código que nos permitía ver todas las columnas de nuestro *DataFrame*.

- 1️⃣ En el *DataFrame* tenemos una columna que nos da la información sobre la fecha de muestreo. Crea dos columnas nuevas a partir de esta, donde una sea el año y otra el mes. ⚠️ El día no lo queremos! 

- 2️⃣ Con la columna creada anteriormente de "mes", crea distintos intervalos para crear una nueva columna que nos indique el trimestre. Deberemos tener 3 trimestres. 

    *HINT*: Antes de hacer cualquier cambio, revisad el tipo de dato que tenemos en nuestras columnas! `pd.cut()` solo acepta integers o floats. 
    
- 3️⃣ Calcula la tasa de cambio de la temperatura de rocío mínima y máxima y crea una nueva columna. 

- 4️⃣ Sobre la columna "trimestre" que creamos en el primer ejercicio queremos crear una columna nueva donde cambiemos: 
    - 1-trimestre por 1
    - 2-trimestre por 2
    - 3-trimestre por 3
    
    ¿Qué método debemos usar?

In [42]:
south = pd.read_csv("files/south.csv", index_col = 0)
south.head(2)

,Data,Hora,"PRECIPITAÇÃO TOTAL, HORÁRIO (mm)","PRESSAO ATMOSFERICA AO NIVEL DA ESTACAO, HORARIA (mB)",PRESSÃO ATMOSFERICA MAX.NA HORA ANT. (AUT) (mB),PRESSÃO ATMOSFERICA MIN. NA HORA ANT. (AUT) (mB),RADIACAO GLOBAL (Kj/m²),"TEMPERATURA DO AR - BULBO SECO, HORARIA (°C)",TEMPERATURA DO PONTO DE ORVALHO (°C),TEMPERATURA MÁXIMA NA HORA ANT. (AUT) (°C),TEMPERATURA MÍNIMA NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MAX. NA HORA ANT. (AUT) (°C),TEMPERATURA ORVALHO MIN. NA HORA ANT. (AUT) (°C),UMIDADE REL. MAX. NA HORA ANT. (AUT) (%),UMIDADE REL. MIN. NA HORA ANT. (AUT) (%),"UMIDADE RELATIVA DO AR, HORARIA (%)","VENTO, DIREÇÃO HORARIA (gr) (° (gr))","VENTO, RAJADA MAXIMA (m/s)","VENTO, VELOCIDADE HORARIA (m/s)",region,state,station,station_code,latitude,longitude,height
index,,,,,,,,,,,,,,,,,,,,,,,,,,
0,2000-09-22,00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S,RS,PORTO ALEGRE,A801,-30.05,-51.166667,46.97
1,2000-09-22,01:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S,NaN,PORTO ALEGRE,A801,-30.05,-51.166667,46.97

In [41]:
from datetime import datetime

In [43]:
nuevas_col = {col:col.strip().lower().replace(' ', '_') for col in south.columns}
south.rename(columns=nuevas_col, inplace =True)

In [45]:
south.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10023 entries, 0 to 707
Data columns (total 26 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   data                                                   10023 non-null  object
 1   hora                                                   10023 non-null  object
 2   precipitação_total,_horário_(mm)                       9040 non-null   float64
 3   pressao_atmosferica_ao_nivel_da_estacao,_horaria_(mb)  9037 non-null   float64
 4   pressão_atmosferica_max.na_hora_ant._(aut)_(mb)        8943 non-null   float64
 5   pressão_atmosferica_min._na_hora_ant._(aut)_(mb)       8943 non-null   float64
 6   radiacao_global_(kj/m²)                                5267 non-null   float64
 7   temperatura_do_ar_-_bulbo_seco,_horaria_(°c)           9042 non-null   float64
 8   temperatura_do_ponto_de_orvalho_(°c)                   9042 non-null   float64
 9   temperatura_máxima_na_hora_ant._(aut)_(°c)             8943 non-null   float64
 10  temperatura_mínima_na_hora_ant._(aut)_(°c)             8943 non-null   float64
 11  temperatura_orvalho_max._na_hora_ant._(aut)_(°c)       8943 non-null   float64
 12  temperatura_orvalho_min._na_hora_ant._(aut)_(°c)       8943 non-null   float64
 13  umidade_rel._max._na_hora_ant._(aut)_(%)               8943 non-null   float64
 14  umidade_rel._min._na_hora_ant._(aut)_(%)               8943 non-null   float64
 15  umidade_relativa_do_ar,_horaria_(%)                    9042 non-null   float64
 16  vento,_direção_horaria_(gr)_(°_(gr))                   8951 non-null   float64
 17  vento,_rajada_maxima_(m/s)                             8941 non-null   float64
 18  vento,_velocidade_horaria_(m/s)                        9039 non-null   float64
 19  region                                                 6871 non-null   object
 20  state                                                  6837 non-null   object
 21  station                                                6830 non-null   object
 22  station_code                                           10023 non-null  object
 23  latitude                                               10023 non-null  float64
 24  longitude                                              10023 non-null  float64
 25  height                                                 10023 non-null  float64
dtypes: float64(20), object(6)
memory usage: 2.1+ MB

In [ ]:
df["national_accounts_reference_year"] = df["national_accounts_reference_year"].astype('Int64', errors = "ignore")

In [47]:
south['data'] = pd.to_datetime(south['data'],errors = "raise")

In [49]:
south['month'] = south['data'].dt.month
south['year'] = south['data'].dt.year

In [53]:
south.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10023 entries, 0 to 707
Data columns (total 28 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   data                                                   10023 non-null  datetime64[ns]
 1   hora                                                   10023 non-null  object
 2   precipitação_total,_horário_(mm)                       9040 non-null   float64
 3   pressao_atmosferica_ao_nivel_da_estacao,_horaria_(mb)  9037 non-null   float64
 4   pressão_atmosferica_max.na_hora_ant._(aut)_(mb)        8943 non-null   float64
 5   pressão_atmosferica_min._na_hora_ant._(aut)_(mb)       8943 non-null   float64
 6   radiacao_global_(kj/m²)                                5267 non-null   float64
 7   temperatura_do_ar_-_bulbo_seco,_horaria_(°c)           9042 non-null   float64
 8   temperatura_do_ponto_de_orvalho_(°c)                   9042 non-null   float64
 9   temperatura_máxima_na_hora_ant._(aut)_(°c)             8943 non-null   float64
 10  temperatura_mínima_na_hora_ant._(aut)_(°c)             8943 non-null   float64
 11  temperatura_orvalho_max._na_hora_ant._(aut)_(°c)       8943 non-null   float64
 12  temperatura_orvalho_min._na_hora_ant._(aut)_(°c)       8943 non-null   float64
 13  umidade_rel._max._na_hora_ant._(aut)_(%)               8943 non-null   float64
 14  umidade_rel._min._na_hora_ant._(aut)_(%)               8943 non-null   float64
 15  umidade_relativa_do_ar,_horaria_(%)                    9042 non-null   float64
 16  vento,_direção_horaria_(gr)_(°_(gr))                   8951 non-null   float64
 17  vento,_rajada_maxima_(m/s)                             8941 non-null   float64
 18  vento,_velocidade_horaria_(m/s)                        9039 non-null   float64
 19  region                                                 6871 non-null   object
 20  state                                                  6837 non-null   object
 21  station                                                6830 non-null   object
 22  station_code                                           10023 non-null  object
 23  latitude                                               10023 non-null  float64
 24  longitude                                              10023 non-null  float64
 25  height                                                 10023 non-null  float64
 26  month                                                  10023 non-null  int64
 27  year                                                   10023 non-null  int64
dtypes: datetime64[ns](1), float64(20), int64(2), object(5)
memory usage: 2.2+ MB

In [58]:
south['trimestre'] = pd.cut(south['month'], 4, labels = ["1º trimestre", "2º trimestre", "3º trimestre", "4º trimestre"])

In [59]:
south['trimestre'].dtype

CategoricalDtype(categories=['1º trimestre', '2º trimestre', '3º trimestre',
                  '4º trimestre'],
, ordered=True)